# A gitRepo volume is basically an emptyDir volume that gets populated by 
# cloning a Git repository and checking out a specific revision 
# when the pod is starting up
# the volume is only populated by the git repo on the startup of the volume
apiVersion: v1
kind: Pod
metadata:
  name: gitrepo-volume-pod
spec:
  containers:
  - image: nginx:alpine
    name: web-server
    volumeMounts:
    - name: html
      mountPath: /usr/share/nginx/html
      readOnly: true
    ports:
    - containerPort: 80
      protocol: TCP
  volumes:
  - name: html
    gitRepo:                                                           
      repository: https://github.com/luksa/kubia-website-example.git   
      revision: master                                                 
      directory: .             