apiVersion: v1
kind: Service
metadata:
  name: kubia
spec:
  ports:
  # The port this service will be available on
  - name: http 
    port: 80
  # the container port the service will forward to
    targetPort: 8080
  - name: https
    port: 443
    targetPort: 8443
  # all pods with app=kubia will be part of this service
  selector:
    app: kubia