apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: kubia
spec:
  serviceName: kubia
  replicas: 2
  template:
  # Pods created by the StatefulSet will have the app=kubia label.
    metadata:
      labels:                        
        app: kubia                   
    spec:
      containers:
      - name: kubia
        image: luksa/kubia-pet
        ports:
        - name: http
          containerPort: 8080
          # The container inside the pod will mount the pvc volume at this path.
        volumeMounts:
        - name: data                 
          mountPath: /var/data       
  volumeClaimTemplates:
  # The PersistentVolumeClaims will be created from this template.
  - metadata:                        
      name: data                     
    spec:                            
      resources:                     
        requests:                    
          storage: 1Mi               
      accessModes:                   
      - ReadWriteOnce                